name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
        with:
          cache: true

      - name: Run script
        run: bun index.js

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun install
          yarn build
